// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIRs45qHhK3BMsfzO_I9frKU_cD10MhaI',
    appId: '1:584924404463:web:2182e94a4895078fce191a',
    messagingSenderId: '584924404463',
    projectId: 'brainclash-145c2',
    authDomain: 'brainclash-145c2.firebaseapp.com',
    storageBucket: 'brainclash-145c2.firebasestorage.app',
    measurementId: 'G-SMR3DG3ZG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw8rayJsf0VxBBJGA4tG8GeX7q-WjQAn8',
    appId: '1:584924404463:android:68bd87a3be14a8d3ce191a',
    messagingSenderId: '584924404463',
    projectId: 'brainclash-145c2',
    storageBucket: 'brainclash-145c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDupwS0NzB821kXCBjqiZxakId6q0a-Hpk',
    appId: '1:584924404463:ios:e5c4c7c667342759ce191a',
    messagingSenderId: '584924404463',
    projectId: 'brainclash-145c2',
    storageBucket: 'brainclash-145c2.firebasestorage.app',
    iosBundleId: 'com.example.flutterBrainclash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDupwS0NzB821kXCBjqiZxakId6q0a-Hpk',
    appId: '1:584924404463:ios:e5c4c7c667342759ce191a',
    messagingSenderId: '584924404463',
    projectId: 'brainclash-145c2',
    storageBucket: 'brainclash-145c2.firebasestorage.app',
    iosBundleId: 'com.example.flutterBrainclash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIRs45qHhK3BMsfzO_I9frKU_cD10MhaI',
    appId: '1:584924404463:web:ca0a5a04c0a888dace191a',
    messagingSenderId: '584924404463',
    projectId: 'brainclash-145c2',
    authDomain: 'brainclash-145c2.firebaseapp.com',
    storageBucket: 'brainclash-145c2.firebasestorage.app',
    measurementId: 'G-11KKYHCG5E',
  );
}
